In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt

#需要修改地址
src_fdr = '/home/ljy/repos/patchV1/src/'
tmp_fdr = '/home/ljy/repos/patchV1/src/tmp/'
res_fdr = '/home/ljy/data/resource_tmp/'

# 修改环境变量
1. 参考src_fdr下的environment_variable.txt，要根据自己的服务器修改CPLUS_INCLUDE_PATH、LD_LIBRARY_PATH、LIBRARY_PATH、CUDA_LIB等
2. 在~/.bashrc中修改环境变量
3. source ~/.bashrc 或者重启，更新环境变量

# 进行编译
其中sm需要根据不同的gpu修改

In [2]:
#修改CUDA_LIB，和环境变量保持一致
os.system(f'cd {src_fdr}/ && ./compile-nonhpc')

./compile-nonhpc: line 10: /home/ljy/miniconda3/envs/neuro/lib/: Is a directory
patch.cu(4407): warning: variable "get_excRangeBound" was declared but never referenced

patch.cu(1342): warning: variable "simpleContrast" was declared but never referenced

ptxas info    : 221856 bytes gmem, 72 bytes cmem[3]
ptxas info    : Compiling entry function '_Z17cudaMemsetNonzeroIfEvPT_jS0_' for 'sm_75'
ptxas info    : Function properties for _Z17cudaMemsetNonzeroIfEvPT_jS0_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 10 registers, 368 bytes cmem[0]
ptxas info    : 223417 bytes gmem, 72 bytes cmem[3]
ptxas info    : Compiling entry function '_Z19recal_G_mat_nd_fastPfPjS0_S_S_S_S_S0_S0_S_S_S_S_S_S_S_S_S_S_S_S_S_S0_P19curandStateMRG32k3aS_S_S_f16ConductanceShapeS3_jjjjjjijjjjj14LearnVarShapeE14LearnVarShapeQjjb' for 'sm_75'
ptxas info    : Function properties for _Z19recal_G_mat_nd_fastPfPjS0_S_S_S_S_S0_S0_S_S_S_S_S_S_S_S_S_S_S_S_S_S0_P19curandStateMRG32k3

0

In [3]:
os.system(f'cd {src_fdr}/ && ./gompile-nonhpc')

ptxas info    : 221728 bytes gmem, 88 bytes cmem[3]
ptxas info    : Function properties for _Z4passfff
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Function properties for _Z6OPpreffff
    24 bytes stack frame, 24 bytes spill stores, 24 bytes spill loads
ptxas info    : Function properties for _Z6ODpreffff
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : 220044 bytes gmem, 72 bytes cmem[3]
ptxas info    : Compiling entry function '_Z17generate_symmetryPjS_PiPfS_S1_S_P19curandStateMRG32k3aS_S1_jjjjjjjjjj' for 'sm_75'
ptxas info    : Function properties for _Z17generate_symmetryPjS_PiPfS_S1_S_P19curandStateMRG32k3aS_S1_jjjjjjjjjj
    32 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 64 registers, 472 bytes cmem[0], 8 bytes cmem[2]
ptxas info    : Compiling entry function '_Z20generate_connectionsPdPfS0_S0_S0_PjS1_S1_S1_S1_S0_S0_S0_S0_S0_S0_S0_S0_S0_S1_S1_S0_S0_S1_S1_S1_S1_S1_S1_S0_S

0

In [4]:
os.system(f'cd {src_fdr}/ && ./rompile-nonhpc')

retinotopic_connections.cu(903): warning: missing return statement at end of non-void function "lambda []()->RFtype"

retinotopic_connections.cu(939): warning: missing return statement at end of non-void function "lambda [](RFtype)->OutputType"

retinotopic_connections.cu(1088): warning: variable "ic_max" was set but never used

retinotopic_connections.cu(1089): warning: variable "is_max" was set but never used

ptxas info    : 223062 bytes gmem, 72 bytes cmem[3]
ptxas info    : Compiling entry function '_Z12vf_pool_CUDAPfS_S_S_S_S_S_S_PjS0_jjjjmfj' for 'sm_75'
ptxas info    : Function properties for _Z12vf_pool_CUDAPfS_S_S_S_S_S_S_PjS0_jjjjmfj
    128 bytes stack frame, 100 bytes spill stores, 272 bytes spill loads
ptxas info    : Used 64 registers, 464 bytes cmem[0], 56 bytes cmem[2]
retinotopic_connections.cu(903): warning: missing return statement at end of non-void function "lambda []()->RFtype"

retinotopic_connections.cu(939): warning: missing return statement at end of non-void

0

# resource文件

In [5]:
#注意修改地址，三个地址应该一致
#创建文件夹
os.system(f'mkdir {res_fdr}')
#运行ext_input_tmp.py 生成图像
os.system(f'cd {tmp_fdr}/ && python ext_input_tmp.py {res_fdr}')
#运行pinwheel_disk_tmp.py 生成resource文件
os.system(f'cd {tmp_fdr} && python pinwheel_disk_tmp.py {res_fdr}')


mkdir: cannot create directory ‘/home/ljy/data/resource_tmp/’: File exists


lum in LMS = [0.45436904 0.47353315 0.0720978 ]
[[1.31265115 0.37916654 0.17658182]
 [0.37916654 0.43588297 0.06613005]
 [0.17658182 0.06613005 1.03101131]]
[[10.82668925 -2.48855249  0.0461736 ]
 [-2.48855249  1.38614356 -0.12768065]
 [ 0.0461736  -0.12768065  1.15767798]]
/home/ljy/data/resource_tmp/
32 degree per pixel
crest in sRGB: [1.33812324 0.27949648 0.72012624]
valley in sRGB: [-9.61030551  0.94753945  0.68825061]
0.005343945578232466 degree per pixel
ecc = 0.0344, buffer_ecc = 0.05110312925171946
1
adjusted to 1 frames in total
sharpness=1.0
it: 0
sRGB space is not enough to represent the color
(array([-9.48965661,  0.28566867,  0.68836448]), array([1.3353379 , 0.94619346, 0.72001885]))
/home/ljy/data/resource_tmp/
average areal CMF within 2 degree eccentricity  = 0.116 deg2/mm2
 0.25 mm ~ 0.085 deg with averaged CMF within 2 degree 
Dow et. al., 1985 integration through linear CMF: 0.25 mm ~ 0.17160 deg
Dow et. al., 1981 integration through inversed foveal linear CMF: 0.25 

0

# 运行retino和genCon

In [6]:
#test_lgn_tmp.cfg 中的resourceFolder需要修改，和之前一致
os.system(f'cd {res_fdr} && retino -c {tmp_fdr}test_lgn_tmp.cfg')
#test_v1_tmp.cfg 中的resourceFolder和inputFolder需要修改，和之前一致
os.system(f'cd {res_fdr} && genCon -c {tmp_fdr}test_v1_tmp.cfg')



Using configuration file: /home/ljy/repos/patchV1/src/tmp/test_lgn_tmp.cfg
CUDA device [NVIDIA GeForce RTX 2080 Ti] has 68 Multi-Processors SM 7.5
total global memory: 11019.562500 Mb.
maximum threads per MP: 1024.
shared memory per block: 49152 bytes.
registers per block: 65536.

5 x 1024 = 5120 post-synaptic neurons
V1_x: [-0.0101148, 0.0101167]
V1_y: [-0.0101168, 0.0101169]
512 LGN neurons, 512 from left eye, 0 from right eye.
need 0mb
LGN_x: [-0.0338376, 0.0335363]
LGN_y: [-0.0339028, 0.032685]
carts ready
left eye: 5120 V1 neurons
right eye: 0 V1 neurons
max pool of LGN = 1024
poolList need memory of 5120x1024x4 = 20971520 = 20mb
need global memory of 20.1406mb in total
vf_pool_CUDA<<<5, 1024>>> (Ipsi)
vf_pool_CUDA<<<0, 1024>>> (Contra)
LGN_V1_RFratio = 0.5
ecc = [0.000127278, 0.00683016, 0.0101169] deg
a = [0.0191669, 0.0508145, 0.0941305] deg
baRatio = [1.2, 1.2, 1.2] deg
R = [0.0372149, 0.0986628, 0.182766] deg
right poolSizes: [1024, 0, 0 < 1024]
among them 0 would have no con

0

# 运行minimalTC

In [9]:
##########################################################################################
# 修改minimalTC_debug中8-13行的地址
# cfg_fdr 表示 test_lgn_xxx.cfg、test_v1_xxx.cfg、minimal_xxx.cfg存放地址
# fdr0 是存放数据文件的地址
# res_fdr 是存放ext_input和pinwheel生成的文件的地址, 一般为fdr0/resource_xxx
# setup_fdr 是存放retino和genCon生成的文件的地址, 一般为fdr0/setup_xxx
# data_fdr 是存放patch_fast生成的文件的地址, 一般为fdr0/data_xxx
# 在debug和tmp测试中，我把res_fdr、setup_fdr、data_fdr统一为同一个文件夹
# ★可以在 fig_fdr/log 看log文件，观察是哪里报错了 (fig_dir在minimalTC_debug中查找)
############################################################################################
os.system(f'cd {tmp_fdr} && ./minimalTC_tmp')

tmp
overwrite contents in /home/ljy/data/resource_tmp
overwrite contents in /home/ljy/data/tmp
configuration files copied
one_ori=1
plotting files copied
python /home/ljy/data/tmp/generate_input_tmp.py tmp_1 tmp minimal-patch test_lgn test_v1 /home/ljy/data/resource_tmp /home/ljy/data/resource_tmp /home/ljy/data/resource_tmp 8 1 sample_OutAndInputCount_
tmp_1
tmp
minimal-patch
test_lgn
test_v1
/home/ljy/data/resource_tmp
/home/ljy/data/resource_tmp
/home/ljy/data/resource_tmp
8.0
1
sample_OutAndInputCount_


0

# 读取文件

In [10]:
setup_fdr = res_fdr
data_fdr = res_fdr
output_suffix = 'tmp'
#读取文件
with open(data_fdr+'sample_OutAndInputCount_'+output_suffix+'_1.bin') as f:
    sampleSize = np.fromfile(f,'u4',1)[0]
    sample_t0, sample_t1 = np.fromfile(f, 'f4', 2)
    sampleID = np.fromfile(f,'u4',sampleSize)
    sample_spikeCount = np.fromfile(f,'u4',sampleSize)
    F0 = np.fromfile(f,'f4',sampleSize)
    F1 = np.fromfile(f,'f4',sampleSize)   
print(sampleSize,sample_t0,sample_t1,sampleID,sample_spikeCount,F0,F1)

3840 0.0 1000.0 [   0    1    2 ... 4861 4862 4863] [14  1  0 ...  5 11  1] [0.12956887 0.         0.00344423 ... 0.         0.         0.10181297] [0.0064993  0.         0.00052702 ... 0.         0.         0.00228142]
